ADC1:
  enabled: true
  differential: false
  gain: "GAIN_2"
  data_rate: "3750SPS"
  RST_PIN: 24
  CS_PIN: 8        
  DRDY_PIN: 22
  channels:
    0: "pt2"
    1: "pt1"
    2: "pt9"
    3: "pt3"
    4: "pt4"
    5: "pt5"
    6: "pt6"
    7: "pt7"

ADC2:
  enabled: true
  differential: false
  gain: "GAIN_1"
  data_rate: "3750SPS"
  RST_PIN: 25
  CS_PIN: 7 
  DRDY_PIN: 23
  channels:
    0: "pt8"
    1: "continuity_raw"
    2: "pt25"
    3: null
    4: null
    5: null
    6: null
    7: null

sensors:
  pt1:
    zero: -1031.4
    scale: 3071.4
  pt2:
    zero: -283.77
    scale: 918.83
  pt3:
    zero: -2257.8
    scale: 6562.1
  pt4:
    zero: -2257.8
    scale: 6562.1
  pt5:
    zero: -623.71
    scale: 1918
  pt6:
    zero: -158.01
    scale: 573.23
  pt7:
    zero: -158.01
    scale: 573.23
  pt8:
    zero: -158.01
    scale: 573.23
  pt9:
    zero: -188.96
    scale: 658.39
  pt25:
    zero: -2257.8
    scale: 6562.1
  continuity_raw:
    zero: 0
    scale: 1